[package]
name = "openrust_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
bytes = "1.4.0"
bzip2 = "0.4.4"
crc32fast = "1.3.2"
flate2 = "1.0.25"
num-bigint = "0.4.3"
whirlpool = "0.10.4"