[package]
name = "openrust_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
byteorder = "1.4.3"
futures = "0.3.28"
openrust_fs = { path = "../openrust_fs" }
tokio = { version = "1.27.0", features = ["full"] }
tokio-util = { version = "0.7.7", features = ["full"] }